Learning Strategies for Poker with a Genetic Algorithm
================
Raphaël Morsomme
2019-01-23

-   [Introduction](#introduction)
-   [Background](#background)
    -   [A Simple Version of Poker](#a-simple-version-of-poker)
    -   [Representation of Strategies](#representation-of-strategies)
    -   [Simulating a Hand](#simulating-a-hand)
        -   [Setup](#setup)
        -   [The Naive Approach](#the-naive-approach)
        -   [The Matrix-Oriented Approach](#the-matrix-oriented-approach)
-   [The Genetic Algorithm](#the-genetic-algorithm)
    -   [Overview](#overview)
    -   [Population of Strategies](#population-of-strategies)
        -   [Cleaning Player B's Strategies](#cleaning-player-bs-strategies)
    -   [Fitness of a Strategy](#fitness-of-a-strategy)
        -   [Confrontations: one v. one](#confrontations-one-v.-one)
        -   [Confrontations: all v. all](#confrontations-all-v.-all)
    -   [Generating New Strategies](#generating-new-strategies)
        -   [Parent Selection](#parent-selection)
        -   [Children Generation](#children-generation)
        -   [`generate_A()` and `generate_B()`](#generate_a-and-generate_b)
-   [The Genetic Algorithm in Action](#the-genetic-algorithm-in-action)

``` r
library(tidyverse)
library(gdata)
```

Introduction
============

In this script, I use a genetic algorithm (GA) to learn strategies for a fairly simple version of poker. I investigate poker because I love playing this game, and to use a GA because it offers a nice coding challenge and is a suitable method for learning good strategies for this game. Compared to gradient-descent-based learning methods, it is less likely to be trapped into local minima. A question that I want to answer at the end of the script is *what conditions encourage people to bluff*.

Background
==========

A Simple Version of Poker
-------------------------

We consider a fairly simple version of poker with only two players: player A and player B. A hand starts with each player paying an *ante* (small predetermined amount) and receiving a single card. Player A then effectuates a *bet* and player B decides to either *fold* or *call*. If player B folds, then player A wins the hand and recuperates the pot (two antes). If player B calls, then the players show their cards, and the one with the highest card wins the hand and recuperates the pots (two antes and two bets). If player B calls and both players have the same card, they simply share the pot.

In short, a hand follows **5 steps** in which we determine:

1.  **Player A's bet** based on player A's strategy and player A's card.
2.  **Player B's action** based on player B's strategy, player B's card and player A's bet.
3.  **The size of the pot** based on player A's bet and player B's action.
4.  **The winner of the hand** given player B's action and the cards of the two players.
5.  **The gain/loss** of each player at the end of the hand.

Before delving into the GA itself, we examine the representation of the strategies, and how to simulate a hand.

Representation of Strategies
----------------------------

Player A's strategy is represented with a vector of numerical values indicating the amount to bet for each card (s)he could receive. If we consider a game where player A can effectuate the following bets 0, 2, 4, 6, 8, 10 and the cards are 1, 2, 3, 4, the following is a possible strategy for player A

    ##   Strategy A
    ## 1          0
    ## 2         10
    ## 3          2
    ## 4          8

which prescribes to bet `0` for a card `1`, `10` (a bluff!) for a `2`, `2` for a `3`, and to bet `8` for a card `4`.

Player B's strategy is represented with a matrix whose entries indicate the action to realize - to *fold* or to *call* - for each possible combination of her/his card (columns) and player A's bet (rows). The following is a possible strategy for player B

    ## , , Strategy B
    ## 
    ##    1      2      3      4     
    ## 0  "Fold" "Fold" "Fold" "Fold"
    ## 2  "Fold" "Fold" "Call" "Fold"
    ## 4  "Call" "Call" "Fold" "Call"
    ## 6  "Fold" "Fold" "Call" "Fold"
    ## 8  "Call" "Call" "Call" "Fold"
    ## 10 "Fold" "Call" "Fold" "Call"

which prescribes to `fold` if (s)he receives a card `1` and player A bets `0`, to `call` if (s)he receives a `2` and player A bets `4` and to `call` if (s)he receives a `4` and player A bets `10`.

Simulating a Hand
-----------------

### Setup

We assign the value of the ante, the cards we play with and the possible bets for player A to the objects `ante`, `cards` and `bets` respectively.

``` r
ante   <- 2
cards  <- 1:4        
bets   <- seq(from = 0, to = 10, by = 2)

# for convenience
n_card      <- length(cards)
n_bet       <- length(bets)
dim_mat     <- c(n_card, n_card)  # (see matrix-oriented approach)
dimname_mat <- list(cards, cards) # (see matrix-oriented approach)
```

We also use `sample()` in `array()` to create random strategies for the two players and assign them to `strategy_A` and `strategy_B`.

``` r
set.seed(123)
strategy_A <- array(data = sample(x = bets, size = n_card, replace = TRUE), 
                    dim = c(n_card, 1), dimnames = list(cards, "Strategy A"))
strategy_B <- array(data = sample(x = c("Call", "Fold"), size = n_card * n_bet, replace = TRUE),
                    dim=c(n_card, n_bet, 1), dimnames = list(cards, bets, "Strategy B"))

# Random strategy for player A
print(strategy_A)
```

    ##   Strategy A
    ## 1          2
    ## 2          8
    ## 3          4
    ## 4         10

``` r
# Random strategy for player B
print(strategy_B)
```

    ## , , Strategy B
    ## 
    ##   0      2      4      6      8      10    
    ## 1 "Fold" "Fold" "Fold" "Call" "Fold" "Fold"
    ## 2 "Call" "Call" "Fold" "Call" "Fold" "Fold"
    ## 3 "Fold" "Fold" "Call" "Call" "Fold" "Fold"
    ## 4 "Fold" "Call" "Fold" "Fold" "Fold" "Fold"

### The Naive Approach

To simulate a hand, one could be tempted to imitate what would happen if two players sat down around a table to play a hand. The (fatal) drawback of this approach (see code in `Appendix - Naive Approach for Simulating a Hand`) is that, to simulate a large number of hands, we need to use loops (painfully slow on `R`). Since the GA requires us to simulate a huge number of hands, we need to come up with a more efficient approach.

### The Matrix-Oriented Approach

The *matrix-oriented* approach uses matrices and matrix operations (fast on `R`) to simulate a large number of hands at once. We use five matrices (one for each step of a hand) whose columns and rows respectively correspond to player A's and player B's cards. This way, we can simulate all possible hands between two given strategies at once. This makes the matrix-oriented approach much more efficient than the naive one. The matrices' entries respectively represent (i) player A's bet (ii) player B's action (iii) the pot size (iv) the winner of the hand and (v) player A's gain/loss.

**1. Determining player A's bet**

The matrix `bet_A` represents player A's bet for each possible hand. Since player A's bet depends only on her/his card, each column of `bet_A` contains the same values.

``` r
bet_A <- array(rep(strategy_A, each = n_card), dim = dim_mat, dimnames = dimname_mat)
# Player A's bet
print(bet_A)
```

    ##   1 2 3  4
    ## 1 2 8 4 10
    ## 2 2 8 4 10
    ## 3 2 8 4 10
    ## 4 2 8 4 10

**2. Determining player B's action**

The matrix `action_B` represents player B's action. Since each column of `bet_A` contains the same values, `action_B` is simply a re-ordering of `strategy_B`'s columns.

``` r
action_B <- array(strategy_B[ , match(x = strategy_A, table = bets), 1], dim = dim_mat, dimnames = dimname_mat)

# Player B's action
print(action_B)
```

    ##   1      2      3      4     
    ## 1 "Fold" "Fold" "Fold" "Fold"
    ## 2 "Call" "Fold" "Fold" "Fold"
    ## 3 "Fold" "Fold" "Call" "Fold"
    ## 4 "Call" "Fold" "Fold" "Fold"

**3. Determining the size of the pot**

`pot_size` represents the size or the pot. If player B folds, then the pot only consists of two antes.

``` r
pot_size                     <- 2 * ante + 2 * bet_A 
pot_size[action_B == "Fold"] <- 2 * ante

# Size of the pot
print(pot_size)
```

    ##   1 2  3 4
    ## 1 4 4  4 4
    ## 2 8 4  4 4
    ## 3 4 4 12 4
    ## 4 8 4  4 4

**4.Determining the winner of hand**

`win_game` indicates the winner of the hand (`1`: player A wins, `0`: a draw and `-1`: player B wins).

``` r
win_game <- array(0, dim = dim_mat, dimnames = dimname_mat)

upperTriangle(win_game, diag = F) <-  1
lowerTriangle(win_game, diag = F) <- -1

win_game[action_B == "Fold"] <- 1

# Winner of the hand
print(win_game)
```

    ##    1 2 3 4
    ## 1  1 1 1 1
    ## 2 -1 1 1 1
    ## 3  1 1 0 1
    ## 4 -1 1 1 1

**5. Determining player A's gain/loss**

`gain_A` represents the gains of player A at the end of the hand. A negative amount indicates that player A loses money. Since this is a zero-sum game between two players, player B's gain/loss is simply the opposite of player A's.

``` r
gain_A <- pot_size * win_game / 2
# Player A's gain/loss
print(gain_A)
```

    ##    1 2 3 4
    ## 1  2 2 2 2
    ## 2 -4 2 2 2
    ## 3  2 2 0 2
    ## 4 -4 2 2 2

``` r
# Player B's gain/loss
print(- gain_A)
```

    ##    1  2  3  4
    ## 1 -2 -2 -2 -2
    ## 2  4 -2 -2 -2
    ## 3 -2 -2  0 -2
    ## 4  4 -2 -2 -2

The Genetic Algorithm
=====================

Overview
--------

In order to learn good strategies for our two players, we use a genetic algorithm (GA). Simply put, a GA loosely imitates the process of *natural selection*: from an existing population, the fittest individuals are crossed over to generate new individuals. After several iterations, we obtain a population of fit individuals. In this script, we design a GA that learns profitable strategies for the two poker players. The question that we want to answer is *under which circumstances the GA learns strategies with bluff*.

In practice, we first generate a initial population (a collection) of random strategies for each player. We then make each strategy of player A play against each strategy of player B. Based on the results of these confrontations, we determine how competitive (or fit) each strategy is. Finally, for each player, we cross over the most competitive strategies together to generate a new population (the next generation) of strategies. This way, features that make strategies competitive are passed on to the next generation. The GA algorithm then works in an iterative manner: confrontation, evaluation and generation.

In short, the GA follows **5 steps**:

1.  **Creation of initial populations** of strategies for player A and player B.
2.  **Confrontation between the strategies.**
3.  **Evaluation of the strategies' fitness** based on the results of the confrontations.
4.  **Generation of new populations of strategies** from the fittest strategies.
5.  **Repeat from step 2.**

The following sections explore in more depth the concepts of population of strategies, fitness, confrontation, evaluation and generation of strategies. At the end of the section, we will be able to run the GA.

Population of Strategies
------------------------

A population of strategies is simply a collection of strategies. For player A, it is represented with a matrix where each column correspond to a strategy. For player B, it is represented with a three-dimensional array where each layer (dimension `3`) corresponds to a strategy. The following code creates populations of ten random strategies for player A and player B. To easily identify the strategies, we name them s1, s2, s3, s4, s5, s6, s7, s8, s9, s10.

``` r
n_strategy    <- 10
name_strategy <- paste("s", 1 : n_strategy, sep = "")

dim_pop_A     <- c   (n_card, n_strategy)            # for convenience
dimname_pop_A <- list(cards , name_strategy)         # for convenience
dim_pop_B     <- c   (n_card, n_bet, n_strategy)     # for convenience
dimname_pop_B <- list(cards , bets , name_strategy)  # for convenience

set.seed(123)
pop_A <- array(sample(x = bets, size = prod(dim_pop_A), replace = TRUE),
               dim = dim_pop_A, dimnames = dimname_pop_A)

# Population of random strategies for player A
print(pop_A)
```

    ##   s1 s2 s3 s4 s5 s6 s7 s8 s9 s10
    ## 1  2 10  6  8  2 10  6  2  8   8
    ## 2  8  0  4  6  0  8  8  0  8   2
    ## 3  4  6 10  0  2  6  6 10  0   2
    ## 4 10 10  4 10 10 10  6 10  4   2

``` r
set.seed(123)
pop_B <- array(sample(x = c("Call", "Fold"), size = prod(dim_pop_B), replace = TRUE),
               dim = dim_pop_B, dimnames = dimname_pop_B)

# Population of random strategies for player B (2 strategies)
print(pop_B[ , , 1 : 2])
```

    ## , , s1
    ## 
    ##   0      2      4      6      8      10    
    ## 1 "Call" "Fold" "Fold" "Fold" "Call" "Fold"
    ## 2 "Fold" "Call" "Call" "Fold" "Call" "Fold"
    ## 3 "Call" "Fold" "Fold" "Call" "Call" "Fold"
    ## 4 "Fold" "Fold" "Call" "Fold" "Fold" "Fold"
    ## 
    ## , , s2
    ## 
    ##   0      2      4      6      8      10    
    ## 1 "Fold" "Call" "Fold" "Fold" "Call" "Call"
    ## 2 "Fold" "Call" "Fold" "Call" "Call" "Call"
    ## 3 "Fold" "Fold" "Call" "Call" "Call" "Call"
    ## 4 "Fold" "Fold" "Call" "Call" "Call" "Call"

### Cleaning Player B's Strategies

We can slightly modify player B's strategies to make them more realistic. Following common sense, we impose that player B *calls* if (s)he has the highest card possible (no risk of losing the hand) or if player A bets 0 (nothing to lose by calling).

``` r
clean_pop_B <- function(pop, cards){
  pop[max(cards),    ,] <- "Call"
  pop[          , "0",] <- "Call"
  return(pop)
}

pop_B <- clean_pop_B(pop = pop_B, cards = cards)

# Clean population for player B
print(pop_B[ , , 1 : 2]) # Compare with the strategies before the cleaning (printed above).
```

    ## , , s1
    ## 
    ##   0      2      4      6      8      10    
    ## 1 "Call" "Fold" "Fold" "Fold" "Call" "Fold"
    ## 2 "Call" "Call" "Call" "Fold" "Call" "Fold"
    ## 3 "Call" "Fold" "Fold" "Call" "Call" "Fold"
    ## 4 "Call" "Call" "Call" "Call" "Call" "Call"
    ## 
    ## , , s2
    ## 
    ##   0      2      4      6      8      10    
    ## 1 "Call" "Call" "Fold" "Fold" "Call" "Call"
    ## 2 "Call" "Call" "Fold" "Call" "Call" "Call"
    ## 3 "Call" "Fold" "Call" "Call" "Call" "Call"
    ## 4 "Call" "Call" "Call" "Call" "Call" "Call"

Fitness of a Strategy
---------------------

The notion of *fitness* is central to the GA: it allows the algorithm to select the best performing strategies from which to generate new strategies. In the context of poker, an obvious measure of fitness is *the average amount of money that a strategy yields against the strategies of the other player's population*.

### Confrontations: one v. one

To determine the fitness of a strategy, we must thus determine its average gain/loss against each strategy of the other player's population. The function `confront()` helps us do that. It follows the matrix-oriented approach to simulate all possible hands between two given strategies and then return the average gain/loss for player A. (To make the function `confront()` run faster, we create the matrix `win_game` outside of the function and consequently adapt how we compute the value `gain_A`.)

``` r
win_game <-   win_game <- array(0, dim = dim_mat)
upperTriangle(win_game, diag = F) <- 1
lowerTriangle(win_game, diag = F) <- -1

confront <- function(strategy_A, strategy_B, n_card, dim_mat, bets, ante, win_game){
  
  # Matrix-oriented approach
  bet_A    <- array(rep(strategy_A, each = n_card       ) , dim = dim_mat)
  action_B <- array(strategy_B[ , match(strategy_A, bets)], dim = dim_mat)
  gain_A                     <- (ante + bet_A) * win_game
  gain_A[action_B == "Fold"] <-  ante
  
  # Average gain for player A
  return(mean(gain_A))
  
}
```

Let us look at the function `confront()` in action.

``` r
confront(strategy_A = pop_A[ ,   3],
         strategy_B = pop_B[ , , 1],
         n_card = n_card, dim_mat = dim_mat, bets = bets, ante = ante, win_game = win_game)
```

    ## [1] -0.625

This means that, on average, `strat_A`, wins `-0.625` for each hand played against `strat_B`. Since the matrix-oriented approach simulates each possible hand once, the function `confront()` computes the *true* average gain of `strat_A` when opposed to `strat_B`.

### Confrontations: all v. all

The function `confront_populations()` uses two loops to make each strategy of player A play against each strategy of player B, and returns the result of these confrontations as a matrix. In the loops, we use the function `confront()` to determine the average gain of player A's strategy against that of player B. That value is recorded in the matrix `fitness` whose columns and rows respectively correspond to player A's and player B's strategies.

``` r
fitness <- array(dim      = c   (n_strategy   , n_strategy   ),
                 dimnames = list(name_strategy, name_strategy))

confront_populations <- function(pop_A, pop_B, name_strategy, fitness, n_card,
                                 dim_mat, bets, ante, win_game){
  
  for(strat_a in name_strategy)
    for(strat_b in name_strategy)
      fitness[strat_b, strat_a] <- confront(strategy_A = pop_A[ , strat_a  ],
                                            strategy_B = pop_B[ , , strat_b],
                                            n_card = n_card, dim_mat = dim_mat,
                                            bets = bets, ante = ante, win_game = win_game)

  return(fitness)
    
}
```

Let us look at the function `confront_populations()` in action.

``` r
fitness <- confront_populations(pop_A = pop_A,
                                pop_B = pop_B,
                                fitness = fitness, name_strategy = name_strategy, win_game = win_game, n_card = n_card, dim_mat = dim_mat, bets = bets, ante = ante)

# Average gains of player A's strategies
print(fitness)
```

    ##         s1     s2     s3     s4     s5     s6     s7     s8     s9    s10
    ## s1  -0.250 -0.375 -0.625 -2.125  0.250 -0.875 -0.875 -0.375 -1.750 -1.125
    ## s2   1.125  0.000 -0.500 -0.375  2.125 -0.500 -0.750  2.500 -1.750 -0.750
    ## s3   0.625 -0.250 -0.250 -0.750  0.875 -0.500 -0.500  0.875 -0.625 -0.250
    ## s4   0.250  0.750 -0.125  0.125  1.250 -0.250 -0.250  1.250 -1.875 -1.125
    ## s5   0.250  0.500 -0.375  0.250 -0.250  0.875  1.125 -0.750  0.625  0.000
    ## s6   1.875 -0.250  1.500  2.000  1.875 -0.375 -0.125  2.500  0.250  0.375
    ## s7   1.000  0.500 -0.375 -0.750  1.125  0.250 -0.500  1.125 -0.125  0.000
    ## s8   0.250 -0.125 -0.375 -0.875  1.125 -1.125 -0.875  0.500 -2.125 -1.125
    ## s9   0.875  0.250  0.125 -0.500  1.250 -0.250 -0.250  1.250 -1.750 -1.250
    ## s10  0.875  0.000  0.750 -0.125  1.750 -1.000 -1.000  1.625 -1.625 -0.750

Taking the mean of the columns of the matrix `fitness` gives us the level of fitness player A's strategies; the same operation conducted on the rows of the matrix `- fitness` (the opposite of `fitness`) gives us the level of fitness of player B's strategies.

``` r
# Fitness of player A's strategy
sort(colMeans(fitness), decreasing = TRUE)
```

    ##      s5      s8      s1      s2      s3      s4      s6      s7     s10 
    ##  1.1375  1.0500  0.6875  0.1000 -0.0250 -0.3125 -0.3750 -0.4000 -0.6000 
    ##      s9 
    ## -1.0750

``` r
# Fitness of player B's strategy
sort(rowMeans(-fitness), decreasing = TRUE)
```

    ##      s1      s8      s3      s9      s4     s10      s2      s5      s7 
    ##  0.8125  0.4750  0.0750  0.0250  0.0000 -0.0500 -0.1125 -0.2250 -0.2250 
    ##      s6 
    ## -0.9625

Let us have a closer look at these results and focus on player A' strategies (easier to analyze than player B's). `s5` and `s8` are the best performing strategy. They are conservative strategies with small bets for small cards and large bets for large cards. With `s5`, player A wins on average 1.1375 per hand against player B's strategies; with `s8`, player A wins on average 1.05 per hand. On the opposite spectrum, `s9` and `s10` have the lowest level of fitness. Both strategies prescribe to effectuates large bets for small cards and small bets for large cards. `s10` even prescribes to bet `2` (very small bet) for a `4` (highest card)! Although the large bets for small cards could be bluffs and are thus not bad per se, betting only `2` for the highest card is definitely a bad idea in this one-round version of poker. Player A loses on average 1.075 with `s9` and 0.6 with `s10`.

Generating New Strategies
-------------------------

The generation of new populations of strategies follows **three steps**:

1.  **Parent Selection**
2.  **Crossover**
3.  **Mutation**

For convenience, we use the term *parent strategy* to refer to a strategy from which new strategies are generated and *child strategy* to ref to a newly generated strategy. In the following, we illustrate how to generate five child strategies for player A. The approach is fundamentally the same for player B .

### Parent Selection

We select the `n` fittest strategies of `pop_A` to form the set of parent strategies `parents`. In our example, we select the seven fittest strategies.

``` r
n_parents  <- 7
n_children <- 5

fitness_sorted  <- sort(colMeans(fitness), decreasing  = T)
fitness_parents <- head(fitness_sorted, n_parents)

# Name and fitness of the set of parent strategies
print(fitness_parents)
```

    ##      s5      s8      s1      s2      s3      s4      s6 
    ##  1.1375  1.0500  0.6875  0.1000 -0.0250 -0.3125 -0.3750

``` r
name_parents    <- names(fitness_parents)
parents         <- pop_A[ , names(fitness_parents)]

# Set of parent strategies
print(parents)
```

    ##   s5 s8 s1 s2 s3 s4 s6
    ## 1  2  2  2 10  6  8 10
    ## 2  0  0  8  0  4  6  8
    ## 3  2 10  4  6 10  0  6
    ## 4 10 10 10 10  4 10 10

### Children Generation

To generate child strategies, we uniformly cross over the parent strategies and introduce random mutations. In the crossover step, we probabilistically combine parent strategies, element by element, to generate the child strategies. In other words, the first element of a child strategy corresponds to the first element of a parent strategy, the second element to the second element of a parent strategy, etc. We use the level of fitness to probabilistically determine which parent passes on a given element to a given child strategy, with fitter parent strategies being more likely to be selected. In the mutation step, we alter a small proportion of the elements of the child strategies.

#### Children Generation: Crossover

The matrix `pop_child` represents the population of child strategies. At this stage, its entries indicate the parent strategy from which the corresponding element is inherited. Note that in the function `sample()`, we set `prob = exp(fitness_parents)` to ensure that the probabilities are positive.

``` r
set.seed(123)
pop_child <- array(sample(name_parents, size = n_card * n_children, replace = TRUE,
                          prob = exp(fitness_parents)), # exp() ensures positive probabilities
                  dim      = c   (n_card, n_children),
                  dimnames = list(cards , paste("Child", 1 : n_children)))

# Origin of the element of the child strategies
print(pop_child)
```

    ##   Child 1 Child 2 Child 3 Child 4 Child 5
    ## 1 "s8"    "s6"    "s1"    "s1"    "s5"   
    ## 2 "s2"    "s5"    "s8"    "s1"    "s5"   
    ## 3 "s8"    "s1"    "s6"    "s5"    "s8"   
    ## 4 "s4"    "s4"    "s8"    "s4"    "s6"

The first and the third elements of `Child 1` come from the parent strategy `s8`, the second element of `Child 1` from `s2`, etc.

Next, we loop through the the names of the parent strategies. In the loop, we first assign the parent strategy with the appropriate name to `strategy_parent`. We then assign the location of the elements of `pop_child` that are inherited from `strategy_parent` to `location_parent`. Finally, we substitute the elements inherited from `strategy_parent` with the corresponding elements of `strategy_parent`.

``` r
for(name_parent in name_parents){
  
  strategy_parent <- parents[ , name_parent]
  location_parent <- pop_child == name_parent
  
  pop_child[location_parent] <- rep(strategy_parent, n_children)[location_parent] # use rep() to match dimensions.

}

pop_child <- array(as.numeric(pop_child),
                   dim = c(n_card, n_children),
                   dimnames = list(cards, paste("Child", 1:n_children)))

# Population of children strategies
print(pop_child)
```

    ##   Child 1 Child 2 Child 3 Child 4 Child 5
    ## 1       2      10       2       2       2
    ## 2       0       0       0       8       0
    ## 3      10       4       6       2      10
    ## 4      10      10      10      10      10

#### Children Generation: Mutations

Finally, we introduce random mutations to `pop_child`. We first assign the desired mutation rate to `mutation_rate` and use the function `sample()` with `prob = c(mutation_rate, 1 - mutation_rate)` to create the matrix `mutation_location` which indicates the locations of the mutations. We then use the function `sample()` again to generate the vector `mutation_outcome` which indicates the outcome of the mutations. Finally, we substitute the elements of `pop_child` where a mutation occurs with the values of `mutation_outcome`.

``` r
mutation_rate <- 0.2

mutation_location <- array(sample(c(T, F), size = n_card * n_children, replace = TRUE, 
                                  prob = c(mutation_rate, 1 - mutation_rate)),
                           dim     = c    (n_card, n_children), 
                           dimnames = list(cards , paste("Child", 1 : n_children)))

# Location of mutations
print(mutation_location)
```

    ##   Child 1 Child 2 Child 3 Child 4 Child 5
    ## 1    TRUE   FALSE   FALSE   FALSE   FALSE
    ## 2   FALSE   FALSE   FALSE   FALSE   FALSE
    ## 3   FALSE   FALSE    TRUE   FALSE   FALSE
    ## 4    TRUE   FALSE    TRUE   FALSE   FALSE

``` r
n_mutation       <- sum(mutation_location)
mutation_outcome <- sample(bets, size = n_mutation, replace = TRUE)

# Outcome of mutations
print(mutation_outcome)
```

    ## [1] 0 4 4 4

``` r
pop_child[mutation_location] <- mutation_outcome

# Population of child strategies after mutations
print(pop_child)
```

    ##   Child 1 Child 2 Child 3 Child 4 Child 5
    ## 1       0      10       2       2       2
    ## 2       0       0       0       8       0
    ## 3      10       4       4       2      10
    ## 4       4      10       4      10      10

### `generate_A()` and `generate_B()`

The functions `generate_A()` and `generate_B()` encapsulate these three steps for player A and player B. These functions are the last one we need to be able to run the GA.

``` r
generate_A <- function(fitness, pop, n_parents, dim_pop_A, dimname_pop_A,
                       n_strategy, bets, mutation_rate){
  
  # Parent Selection
  fitness_strategy <- colMeans(fitness)
  fitness_parents  <- head(sort(fitness_strategy, decreasing  = TRUE), n_parents)
  name_parents     <- names(fitness_parents)
  parents          <- pop[ , name_parents]
  
  # Crossover
  pop <- array(sample(name_parents, size = prod(dim_pop_A), replace = T,
                      prob = exp(fitness_parents)),
               dim = dim_pop_A, dimnames = dimname_pop_A)
  
  for(parent in name_parents){
    
    strategy_parent <- parents[ , parent]
    location_parent <- pop == parent
    pop[location_parent] <- rep(strategy_parent, n_strategy)[location_parent]

  }
  
  pop <- array(as.numeric(pop), dim = dim_pop_A, dimnames = dimname_pop_A)
  
  # Mutation
  mutation_location <- array(sample(c(T, F), size = prod(dim_pop_A), TRUE,
                                    prob = c(mutation_rate, 1-mutation_rate)),
                             dim = dim_pop_A, dimnames = dimname_pop_A)
  
  n_mutations      <- sum(mutation_location)
  mutation_outcome <- sample(bets, size = n_mutations, replace = T)
  
  pop[mutation_location] <- mutation_outcome
  
  return(pop)
  
}
```

``` r
generate_B <- function(fitness, pop, n_parents, dim_pop_B, dimname_pop_B,
                       n_strategy, mutation_rate, cards){
  
  # Parent Selection
  fitness          <- - fitness
  fitness_strategy <- rowMeans(fitness)
  fitness_parents  <- head(sort(fitness_strategy, decreasing = TRUE), n_parents)
  name_parents     <- names(fitness_parents)
  parents          <- pop[ , , name_parents]
  
  # Crossover
  pop <- array(sample(name_parents, size = prod(dim_pop_B), replace = TRUE,
                      prob = exp(fitness_parents)),
               dim = dim_pop_B, dimnames = dimname_pop_B)
    
  for(parent in name_parents){
    
    strategy_parent <- parents[ , , parent]
    location_parent <- pop == parent
    
    pop[location_parent] <- rep(strategy_parent, n_strategy)[location_parent]
    
  }
  
  # Mutation
  # Since player B has only two actions i.e. "Call" or "Fold", half of the mutations have no effect. We therefore double the mutation rate.
  mutation_rate <- 2 * mutation_rate 
  mutation_location <- array(sample(c(T, F), size = prod(dim_pop_B), replace = T,
                                    prob = c(mutation_rate, 1-mutation_rate)),
                           dim = dim_pop_B, dimnames = dimname_pop_B)
  
  n_mutations            <- sum(mutation_location)
  mutation_outcome       <- sample(c("Call", "Fold"), n_mutations, T)
  pop[mutation_location] <- mutation_outcome
  
  pop <- clean_pop_B(pop = pop, cards = cards)
  
  return(pop)
  
}
```

Let us look at the function `generate_A` in action.

``` r
# Parent Strategies
print(pop_A) # random bets for small cards
```

    ##   s1 s2 s3 s4 s5 s6 s7 s8 s9 s10
    ## 1  2 10  6  8  2 10  6  2  8   8
    ## 2  8  0  4  6  0  8  8  0  8   2
    ## 3  4  6 10  0  2  6  6 10  0   2
    ## 4 10 10  4 10 10 10  6 10  4   2

``` r
# Child Strategies (small bets for small cards, the GA is already learning good strategies)
generate_A(fitness = fitness, pop = pop_A, n_parents = n_parents,
           dim_pop_A = dim_pop_A, dimname_pop_A = dimname_pop_A,
           n_strategy = n_strategy, bets = bets, mutation_rate = 0.05)
```

    ##   s1 s2 s3 s4 s5 s6 s7 s8 s9 s10
    ## 1  2  2  6  2  2  6  6 10  2   2
    ## 2  0  4  0  0  0  0  0  0  0   8
    ## 3  4  2  4  0 10 10  6 10 10  10
    ## 4 10 10 10 10 10  4 10 10 10  10

The Genetic Algorithm in Action
===============================

Now that we have covered all the components of the GA, we can finally write the function `my_GA` which encapsulates them.

``` r
my_GA <- function(cards = 1:10, bets = seq(0,20,2), ante = 5, n_strategy = 200,
                  n_generations = 10, prop_parents = 2/3, mutation_rate = 0.05){
  
  
  #
  # Setup
  n_card        <- length(cards)
  n_bet         <- length(bets)
  n_parents     <- n_strategy * prop_parents
  
  name_strategy <- paste("s", 1 : n_strategy, sep = "")
  
  dim_pop_A     <- c(n_card, n_strategy)
  dim_pop_B     <- c(n_card, n_bet, n_strategy)
  dim_mat       <- c(n_card, n_card)
  dim_fit       <- c(n_strategy, n_strategy)
  dim_output_A  <- c(dim_pop_A, n_generations)
  dim_output_B  <- c(dim_pop_B, n_generations)
  dim_fit_A     <- c(dim_fit, n_generations)
  
  dimname_pop_A    <- list(cards, name_strategy)
  dimname_pop_B    <- list(cards, bets, name_strategy)
  dimname_mat      <- list(cards, cards)
  dimname_fit      <- list(name_strategy, name_strategy)
  dimname_output_A <- list(cards, name_strategy, 1 : n_generations)
  dimname_output_B <- list(cards, bets, name_strategy, 1 : n_generations)
  dimname_fit_A    <- list(name_strategy, name_strategy, 1 : n_generations)
  
  win_game      <- array(0, dim = dim_mat)
  upperTriangle(win_game, diag = F) <-  1
  lowerTriangle(win_game, diag = F) <- -1
  
  fitness <- array(NA, dim = dim_fit, dimnames = dimname_fit)
  
  output_A  <- array(NA, dim = dim_output_A, dimnames = dimname_output_A)
  output_B  <- array(NA, dim = dim_output_B, dimnames = dimname_output_B)
  fitness_A <- array(NA, dim = dim_fit_A   , dimnames = dimname_fit_A   )
  
  #
  # Initialization
  generation <- 1
  
  pop_A <- array(sample(bets, size = prod(dim_pop_A), replace = TRUE),
                 dim = dim_pop_A, dimnames = dimname_pop_A)
  pop_B <- array(sample(c("Call", "Fold"), size = prod(dim_pop_B), replace = TRUE),
                 dim = dim_pop_B, dimnames = dimname_pop_B)
  pop_B <- clean_pop_B(pop_B, cards = cards)
  
  output_A[ , ,   generation] <- pop_A
  output_B[ , , , generation] <- pop_B
  
  #
  # Loop
  while(generation < n_generations){

    fitness <- confront_populations(pop_A = pop_A, pop_B = pop_B,
                                    name_strategy = name_strategy,
                                    fitness = fitness, n_card = n_card,
                                    dim_mat = dim_mat, bets = bets, 
                                    ante = ante, win_game = win_game)

    pop_A <- generate_A(fitness = fitness, pop = pop_A, n_parents = n_parents,
                        dim_pop_A = dim_pop_A, dimname_pop_A = dimname_pop_A,
                        n_strategy = n_strategy, bets = bets,
                        mutation_rate = mutation_rate)
    
    pop_B <- generate_B(fitness = fitness, pop = pop_B, n_parents = n_parents,
                        dim_pop_B = dim_pop_B, dimname_pop_B = dimname_pop_B,
                        n_strategy = n_strategy, cards = cards,
                        mutation_rate = mutation_rate)
    
    # Output
    fitness_A[ , ,   generation    ] <- fitness
    output_A [ , ,   generation + 1] <- pop_A
    output_B [ , , , generation + 1] <- pop_B
    
    generation <- generation + 1
    
  } # close for-loop
  
  return(list(A   = output_A,
              B   = output_B,
              fit = fitness_A))
  
}
```

Finally, let us look at the GA in action.

``` r
set.seed(123)
results <- my_GA()

results_A <- results$A
results_B <- results$B

# 10 strategies of the 8th generation for player A
results_A[ , 1 : 10, 8]
```

    ##    s1 s2 s3 s4 s5 s6 s7 s8 s9 s10
    ## 1   2  4  2  6  6  2  2  6  2   4
    ## 2   2  2  2  2  2  2  6  2  2   2
    ## 3   2  6  2  6  2 10  0  2  2   6
    ## 4   2  2  2  4  4  4  8  2  6   2
    ## 5   4 14 10  6 20  4  0  4  2  10
    ## 6   6  4  2  6  0 16  2 20  2   2
    ## 7   2 18 14  8  8  8 20  0  4  10
    ## 8   8 14 20 10 12 12 16 12 12  16
    ## 9  18 18 14 20 18 20  6 18 18  14
    ## 10 20 18 16 20 14 18 12 20 16  20

``` r
# 2 strategies of the 10th generation for player B
results_B[ , , 25 : 26, 10]
```

    ## , , s25
    ## 
    ##    0      2      4      6      8      10     12     14     16     18    
    ## 1  "Call" "Fold" "Call" "Fold" "Call" "Fold" "Fold" "Fold" "Fold" "Call"
    ## 2  "Call" "Fold" "Fold" "Call" "Fold" "Call" "Fold" "Fold" "Fold" "Call"
    ## 3  "Call" "Fold" "Fold" "Call" "Fold" "Call" "Fold" "Fold" "Fold" "Fold"
    ## 4  "Call" "Fold" "Call" "Call" "Call" "Call" "Call" "Fold" "Fold" "Fold"
    ## 5  "Call" "Call" "Call" "Call" "Fold" "Call" "Call" "Call" "Call" "Call"
    ## 6  "Call" "Call" "Call" "Call" "Fold" "Call" "Call" "Fold" "Call" "Call"
    ## 7  "Call" "Call" "Call" "Call" "Fold" "Call" "Fold" "Fold" "Fold" "Fold"
    ## 8  "Call" "Call" "Call" "Call" "Call" "Fold" "Fold" "Call" "Call" "Fold"
    ## 9  "Call" "Call" "Call" "Call" "Call" "Fold" "Call" "Call" "Call" "Fold"
    ## 10 "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Call"
    ##    20    
    ## 1  "Fold"
    ## 2  "Fold"
    ## 3  "Call"
    ## 4  "Fold"
    ## 5  "Fold"
    ## 6  "Fold"
    ## 7  "Fold"
    ## 8  "Fold"
    ## 9  "Fold"
    ## 10 "Call"
    ## 
    ## , , s26
    ## 
    ##    0      2      4      6      8      10     12     14     16     18    
    ## 1  "Call" "Call" "Fold" "Fold" "Call" "Fold" "Call" "Fold" "Fold" "Fold"
    ## 2  "Call" "Fold" "Call" "Fold" "Call" "Call" "Call" "Call" "Fold" "Fold"
    ## 3  "Call" "Call" "Call" "Call" "Call" "Call" "Fold" "Fold" "Fold" "Fold"
    ## 4  "Call" "Call" "Fold" "Fold" "Fold" "Fold" "Call" "Fold" "Fold" "Fold"
    ## 5  "Call" "Call" "Call" "Fold" "Fold" "Call" "Call" "Fold" "Fold" "Call"
    ## 6  "Call" "Fold" "Call" "Fold" "Fold" "Fold" "Call" "Fold" "Fold" "Call"
    ## 7  "Call" "Call" "Call" "Call" "Fold" "Call" "Call" "Call" "Fold" "Fold"
    ## 8  "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Fold" "Fold" "Call"
    ## 9  "Call" "Fold" "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Fold"
    ## 10 "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Call" "Call"
    ##    20    
    ## 1  "Call"
    ## 2  "Fold"
    ## 3  "Fold"
    ## 4  "Fold"
    ## 5  "Call"
    ## 6  "Fold"
    ## 7  "Fold"
    ## 8  "Fold"
    ## 9  "Fold"
    ## 10 "Call"
