---
title: "Results"
author: "Raphaël Morsomme"
date: "`r Sys.Date()`"
output:
  github_document:
    toc: TRUE
    fig_height: 4
    fig_width: 8
---

# Introduction
We experiment with the parameters of our GA to answer two questions:

1. **What conditions encourage player A to bluff?**

2. **What trick could player B adopt to discourage player A from bluffing?**

It appears that the size of the ante and the mutation rate have an impact on player A's level of bluff. Large antes make a successful bluff more profitable and are associated with more bluffs from player A, and low mutation rates make player B adopt more cautious strategies (folding for large bets) which encourage player A to bluff. Player B can therefore discourage player A from bluffing by being more *adventurous* (calling large bets more often). After discussing these results, I mention ways to improve the current analysis.

## Defining Bluff
Since in our version of poker only player A can bluff, we exclusively focus on player A's strategy and how often (s)he bluffs. We use a simple definition of bluff: *player A bluffs if (s)he effectuates large bets for small cards*. We assess player A's level of bluff *visually*. The following two plots display two strategies for player A: a strategy with bluff, and a conservative strategy (without bluff). They should guide our interpretation of the results.

```{r, echo = F}
par(mfrow=c(1,2), cex = 1.1)

barplot(c(12, 7, 8, 2, 3, 3, 12, 15, 18, 17),
        names.arg = 1:10,
        ylim = c(0, 20),
        main = "Strategy for Player A with Bluff",
        xlab = "Player A's Card", ylab = "Bet")
abline(h=seq(0,20,2), lty=2)

barplot(c(2, 1, 2, 2, 3, 3, 12, 15, 18, 17),
        names.arg = 1:10,
        ylim = c(0, 20),
        main = "Strategy for Player A without Bluff",
        xlab = "Player A's Card", ylab = "Bet")
abline(h=seq(0,20,2), lty=2)

par(mfrow=c(1,1), cex = 1)
```

# Results
Two factors influence player A's level of bluff: the size of the ante and the mutation rate. We run the GA with three levels of ante (`0`, `5` and `10`) and four levels of mutation rate (`0.001`, `0.01`, `0.05` and `0.1`) for `125` generations. The results are accessible on this Shiny App.

## Ante
The size of the ante determines how profitable it is for player A to bluff. Indeed, if the bluff is successful and player B does not call it, then player A wins the ante. A large ante therefore encourages player A to bluff and a small one has the opposite effect. Following this logic, if `ante = 0`, player A should never bluff since bluffing can only result in a loss: if player B calls the bluff player A risks losing the hand, and if player B does not call the bluff player A wins nothing (ante is `0`).

This is exactly what we find. When the ante is `0`, player A quickly adopts a conservative strategy with no significant bet for small cards (see generation `25` and after). After some time (generation `93` and after), player A's strategies become extremely conservative with *no* bet for cards other than `10`. Note that I have reduced the mutation rate from `0.05` to `0.01` to accentuate this pattern. On the contrary, as we increase the ante to `5` and `10`, player A's level of bluff increases too. See for instance the best strategy of generation `118` (`ante = 0`) with bets of `20` for the two lowest cards.

This shows that, unsurprisingly, the more profitable the bluff, the more player A bluffs. This has, for instance, the following consequence for situations involving negotiation: one should bluff (and expect other people to bluff) only if it is worth it. This means that a way to prevent someone else form bluffing is to convince her/him that bluffing is not worthwhile, that the gain of a bluff are too small for the bluff to be profitable. As for poker, this means that a way to encourage players to bluff (and thereby make the games more exciting) is simply to increase the value of the ante.

## Mutation Rate
The link between stability and bluff is not obvious at first glance (at least it was not to me). Yet, we observe that as the mutation rate decreases, player A's level of bluff increases. Note that if the mutation rate is too small (`0.001`), then the population become too homogeneous and evolve in an erratic fashion. When the mutation rate is large (`0.1`), then player A adopts a conservative strategy.

This is explained by the fact that, when the mutation rate is small, player B adopts a cautious strategy (folding for large bets of player A). In this simulation, it turns out that being cautious is more profitable for player B. See, for instance, generation `37` for `mutation rate = 0.01`, where player B folds for large bets of player A. Hence, a small mutation rate, which means that the child generations of player B *closely* copy their most profitable parent strategies, result in cautious strategies for player B. The adoption of cautious strategies by player B in turn encourages player A to bluff since her/his bluffs will not be called. On the other hand, when the mutation rate is large, player B adopts adventurous strategies (calling large bets of player A more often due to random mutations), discouraging player A from bluffing.

This means that bluffing is most profitable when the other person is cautious and does not call other people's bluffs. A way to protect oneself from the bluffs of others, is therefore to simply be more adventurous and call other people's bluffs more often.

## Other Parameters
I also explored the effect of the other parameters of the GA on player A's level of bluff. I found that they do not influence it. Increasing the number of cards or bets only slows down the algorithm: simulating a generation is computationally more expensive and the patterns need a larger number of generations to appear. The number of strategies in the population also has no impact on player A's level of bluff. Yet, one needs a sufficient amount of strategies in the populations for the algorithm to work. If the number of strategies is too small (`20` for instance), then the strategies struggle to evolve after a few generations. Finally, the proportion of strategies that we select to form the set of parent strategies has to be, to my surprise, relatively large (in this simulation it is `70%`). A small value also results in population that struggle to evolve.

# Looking Forward
The current analysis could be improved in several ways.

## Operationalization
So far, we have conducted a visual assessment of player A's level of bluff. Yet, it would be beneficial to have a numerical measure thereof. This way, we could conduct statistical tests on the results. We could for instance take the distance between player A's strategies and a typically conservative strategy as a measure of player A's level of bluff.

Similarly, we could also come up with a measure of how cautious player B's strategies are. Again, we could take the distance between player B's strategies and some baseline strategy as a measure of player B's level of cautiousness.

## Elitism
Our version of the GA does not include *elitism*. Elitism refers to the practice of carrying forward the best parent strategies (the elites) into the following generation intact. If we set the proportion of elites to, say, `10%`, then the `10%` fittest strategies are kept and the children strategies replace the remaining strategies. Elitism ensures that, regardless of the mutations occurring in the children strategies, we still have good strategies (the elites) in the new population, thereby making the GA more efficient.

## Stochastic Strategies
Finally, we could introduce a *stochastic* element to the strategies of the two players. For player A, this could take the form of a strategy that gives a density distribution (for instance a normal distribution) for each card (s)he could receive. Player A's bet then corresponds to a value randomly chosen according to the density distribution. Such strategy could for instance consists of two vectors providing the mean and  standard deviation of a normal distribution for each possible card. The current version of player A's strategy is a special case of such stochastic strategy where the standard deviations are `0`. As for player B, the strategy could indicate the probability of calling player A's bet given her/his card and player A's bet. The current version of player B's strategy is a special case of such stochastic strategy where the two allowed probabilities are `0` (fold) and `1` (call). Designing strategies containing a stochastic element will be the topic of my next script.